################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/cmsis_os2.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_cfg_app.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_core.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_dbg.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_flag.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_mon.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_msg.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_mutex.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_prio.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_q.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_sem.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_stat.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_task.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_time.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_tmr.c \
/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_var.c 

OBJS += \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/cmsis_os2.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_cfg_app.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_core.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_dbg.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_flag.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_mon.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_msg.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_mutex.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_prio.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_q.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_sem.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_stat.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_task.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_time.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_tmr.o \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_var.o 

C_DEPS += \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/cmsis_os2.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_cfg_app.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_core.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_dbg.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_flag.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_mon.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_msg.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_mutex.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_prio.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_q.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_sem.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_stat.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_task.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_time.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_tmr.d \
./gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_var.d 


# Each subdirectory must supply rules for building sources it contributes
gecko_sdk_4.1.0/platform/micrium_os/kernel/source/cmsis_os2.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/cmsis_os2.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/cmsis_os2.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_cfg_app.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_cfg_app.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_cfg_app.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_core.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_core.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_dbg.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_dbg.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_dbg.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_flag.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_flag.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_flag.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_mon.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_mon.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_mon.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_msg.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_msg.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_msg.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_mutex.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_mutex.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_mutex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_prio.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_prio.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_prio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_q.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_q.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_q.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_sem.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_sem.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_sem.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_stat.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_stat.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_stat.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_task.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_task.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_task.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_time.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_time.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_time.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_tmr.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_tmr.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_tmr.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_var.o: /Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk/platform/micrium_os/kernel/source/os_var.c gecko_sdk_4.1.0/platform/micrium_os/kernel/source/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g3 -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DDEBUG_EFM=1' '-DEFM32GG11B820F2048GL192=1' '-DSL_BOARD_NAME="BRD2204A"' '-DSL_BOARD_REV="B07"' '-DconfigNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2' '-DSL_COMPONENT_CATALOG_PRESENT=1' -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/FatFS/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/SDIO_Driver/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/hall effects/inc" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/config" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta/autogen" -I"/Users/aleboyer/SimplicityStudio/v5_workspace/mod_livewire_control_beta" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/Device/SiliconLabs/EFM32GG11B/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//hardware/board/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/button/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/cli/src" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/Core/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/CMSIS/RTOS2/Include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/device_init/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/common/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emlib/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/emdrv/gpiointerrupt/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/iostream/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/driver/leddrv/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/common/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/cpu/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/ports/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/source" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/micrium_os/kernel/include" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/common/toolchain/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/system/inc" -I"/Users/aleboyer/SimplicityStudio/SDKs/gecko_sdk//platform/service/sleeptimer/inc" -Os -Wall -Wextra -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -c -fmessage-length=0 -MMD -MP -MF"gecko_sdk_4.1.0/platform/micrium_os/kernel/source/os_var.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


